const API="https://archive.org/advancedsearch.php?q=mediatype%3Amovies&fl%5B%5D=identifier&fl%5B%5D=title&fl%5B%5D=year&fl%5B%5D=description&rows=250&page=1&output=json";
const KEY="moviehub40";
const defaults=[{id:"p1",name:"Grimey",avatar:"G"},{id:"p2",name:"Guest",avatar:"★"},{id:"p3",name:"Kids",avatar:"K"},{id:"p4",name:"Family",avatar:"F"}];
const saved=JSON.parse(localStorage.getItem(KEY)||"null")||{profile:"p1",profiles:defaults,list:{},history:{},reactions:{},kids:false};
const S={...saved,all:[],genre:"All",q:"",cur:null,downloadCache:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>(s??"").toString().replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const activeProfile=()=>S.profiles.find(p=>p.id===S.profile)||S.profiles[0];
const profileKey=()=>S.profile;
function save(){localStorage.setItem(KEY,JSON.stringify({profile:S.profile,profiles:S.profiles,list:S.list,history:S.history,reactions:S.reactions,kids:S.kids}))}
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");clearTimeout(window._toast);window._toast=setTimeout(()=>x.classList.remove("show"),1900)}
function poster(id){return"https://archive.org/services/img/"+encodeURIComponent(id)}
function source(id){return"https://archive.org/details/"+encodeURIComponent(id)}
function classify(x){const s=(x.title+" "+(x.description||"")).toLowerCase();if(/horror|vampire|monster|ghost|zombie/.test(s))return"Horror";if(/science fiction|sci-fi|space|robot|future/.test(s))return"Sci-Fi";if(/animation|cartoon/.test(s))return"Animation";if(/documentary|education/.test(s))return"Documentary";if(/western|cowboy/.test(s))return"Western";if(/comedy|funny/.test(s))return"Comedy";if(/adventure|explor/.test(s))return"Adventure";if(/action|war|battle|fight/.test(s))return"Action";if(/drama|love|romance/.test(s))return"Drama";return"Classic"}
async function load(){try{const r=await fetch(API);if(!r.ok)throw 0;const j=await r.json();S.all=(j.response?.docs||[]).map(x=>({id:x.identifier,title:x.title||x.identifier,year:String(x.year||""),desc:typeof x.description==="string"?x.description.replace(/<[^>]+>/g," ").replace(/\s+/g," ").slice(0,650):"",g:classify(x)}));buildGenres();renderHome();renderProfiles();}catch(e){$("#trending").innerHTML='<div class="empty">Catalog unavailable. Refresh while online.</div>'}}
function buildGenres(){const gs=["All","Action","Adventure","Comedy","Drama","Horror","Sci-Fi","Animation","Documentary","Classic","Western"];$("#genres").innerHTML=gs.map(g=>`<button class="chip ${S.genre===g?"active":""}" data-g="${g}">${g}</button>`).join("");$$(".chip").forEach(b=>b.onclick=()=>{S.genre=b.dataset.g;buildGenres();renderHome();if(S.genre!=="All")$("#catalog").scrollIntoView({behavior:"smooth"})})}
function filtered(){return S.all.filter(x=>(S.genre==="All"||x.g===S.genre)&&(!S.q||(x.title+" "+x.year+" "+x.g+" "+x.desc).toLowerCase().includes(S.q.toLowerCase())))}
function card(x,extra=""){const h=S.history[profileKey()]?.[x.id];const pct=h?.duration?Math.min(100,Math.round(h.time/h.duration*100)):0;return`<article class="card" data-id="${esc(x.id)}"><div class="poster"><img loading="lazy" src="${poster(x.id)}" onerror="this.style.display='none';this.nextElementSibling.classList.remove('hidden')"><div class="posterFallback hidden">▶</div><span class="tag">${esc(x.g)}</span>${pct?`<span class="progress"><i style="width:${pct}%"></i></span>`:""}</div><div class="info"><div class="name">${esc(x.title)}</div><div class="meta">${esc(x.year)} · ${esc(x.g)}</div></div></article>`}
function bind(sel){$$(sel+" .card").forEach(c=>c.onclick=()=>detail(c.dataset.id))}
function sortRecent(a){return[...a].sort((x,y)=>Number(y.year||0)-Number(x.year||0))}
function renderHome(){const a=filtered();$("#catalogCount").textContent=a.length+" titles";$("#trending").innerHTML=sortRecent(a).slice(0,24).map(card).join("");$("#topPicks").innerHTML=[...a].sort((x,y)=>(S.reactions[profileKey()]?.[y.id]||0)-(S.reactions[profileKey()]?.[x.id]||0)).slice(0,20).map(card).join("");$("#newAdditions").innerHTML=sortRecent(a).slice(0,20).map(card).join("");const rec=a.filter(x=>!S.list[profileKey()]?.includes(x.id));$("#recommended").innerHTML=(rec.length?rec:a).slice(0,20).map(card).join("");bind("#trending");bind("#topPicks");bind("#newAdditions");bind("#recommended");renderContinue();renderList();renderSearch()}
function renderContinue(){const ids=Object.keys(S.history[profileKey()]||{});const a=ids.map(id=>S.all.find(x=>x.id===id)).filter(Boolean).slice(0,20);$("#continue").innerHTML=a.map(card).join("");$("#continueSection").classList.toggle("hidden",!a.length);bind("#continue")}
function renderList(){const ids=S.list[profileKey()]||[];const a=ids.map(id=>S.all.find(x=>x.id===id)).filter(Boolean);$("#mylist").innerHTML=a.map(card).join("");$("#listEmpty").classList.toggle("hidden",a.length>0);bind("#mylist")}
function renderSearch(){const a=filtered();$("#results").innerHTML=a.map(card).join("");$("#searchEmpty").classList.toggle("hidden",a.length>0);$("#searchHint").textContent=S.q?`${a.length} result${a.length===1?"":"s"} for “${S.q}”`:"Search the catalog by title, year or genre.";bind("#results")}
function detail(id){const m=S.all.find(x=>x.id===id);if(!m)return;S.cur=m;const inList=(S.list[profileKey()]||[]).includes(id);const reaction=S.reactions[profileKey()]?.[id]||0;$("#details").innerHTML=`<div class="detailPoster"><img src="${poster(m.id)}"></div><div class="detail"><h1>${esc(m.title)}</h1><div class="badges"><span class="badge">${esc(m.year||"Year unknown")}</span><span class="badge">${esc(m.g)}</span><span class="badge">MovieHub</span></div><p>${esc(m.desc||"Movie information is provided by the source item record.")}</p><div class="actions"><button class="watch" id="watch">▶ Watch</button><button id="down">⇩ Download</button><button id="my">♡ ${inList?"Remove":"My List"}</button></div><div class="reaction"><button id="like">👍 ${reaction===1?"Liked":"Like"}</button><button id="dislike">👎 ${reaction===-1?"Not for me":"Not for me"}</button></div><div class="source">Source: <a href="${source(m.id)}" target="_blank" rel="noopener">Internet Archive</a>. Verify the rights/license for each title before reuse.</div></div>`;$("#modal").classList.remove("hidden");$("#watch").onclick=()=>play(m);$("#down").onclick=()=>download(m);$("#my").onclick=()=>toggleList(m.id);$("#like").onclick=()=>react(m.id,1);$("#dislike").onclick=()=>react(m.id,-1)}
function toggleList(id){S.list[profileKey()]=S.list[profileKey()]||[];S.list[profileKey()].includes(id)?S.list[profileKey()]=S.list[profileKey()].filter(x=>x!==id):S.list[profileKey()].push(id);save();detail(id);renderHome();toast("My List updated")}
function react(id,v){S.reactions[profileKey()]=S.reactions[profileKey()]||{};S.reactions[profileKey()][id]=S.reactions[profileKey()][id]===v?0:v;save();detail(id);renderHome();toast("Preference saved")}
$("#close").onclick=()=>$("#modal").classList.add("hidden");
async function videoUrl(m){const r=await fetch("https://archive.org/metadata/"+encodeURIComponent(m.id));const j=await r.json();const files=(j.files||[]).filter(x=>/\.(mp4|m4v|webm)$/i.test(x.name)&&!/(sample|thumb|_low|512kb)/i.test(x.name));files.sort((a,b)=>(Number(b.size)||0)-(Number(a.size)||0));if(!files[0])throw 0;return"https://archive.org/download/"+encodeURIComponent(m.id)+"/"+files[0].name.split("/").map(encodeURIComponent).join("/")}
function play(m){videoUrl(m).then(u=>{$("#video").src=u;$("#now").textContent=m.title;$("#status").textContent="Online playback";$("#player").classList.remove("hidden");$("#video").load();$("#video").play().catch(()=>{});restorePosition(m.id)}).catch(()=>toast("No compatible video file found for this title"))}
function restorePosition(id){const h=S.history[profileKey()]?.[id];if(h?.time)$("#video").addEventListener("loadedmetadata",()=>{try{$("#video").currentTime=Math.min(h.time,Math.max(0,$("#video").duration-2))}catch(e){}},{once:true})}
$("#video").addEventListener("timeupdate",()=>{if(!S.cur||!$("#video").duration)return;S.history[profileKey()]=S.history[profileKey()]||{};S.history[profileKey()][S.cur.id]={time:$("#video").currentTime,duration:$("#video").duration};save();$("#seek").value=($("#video").currentTime/$("#video").duration)*100});
$("#video").addEventListener("ended",()=>{if(S.cur&&S.history[profileKey()])delete S.history[profileKey()][S.cur.id];save();renderContinue();$("#playPause").textContent="▶"});
$("#playPause").onclick=()=>{$("#video").paused?$("#video").play():$("#video").pause();$("#playPause").textContent=$("#video").paused?"▶":"Ⅱ"};
$("#back10").onclick=()=>$("#video").currentTime=Math.max(0,$("#video").currentTime-10);
$("#forward10").onclick=()=>$("#video").currentTime=Math.min($("#video").duration||0,$("#video").currentTime+10);
$("#seek").oninput=e=>{if($("#video").duration)$("#video").currentTime=($("#video").duration*e.target.value)/100};
let speeds=[1,.75,1.25,1.5,2],speedIndex=0;$("#speedBtn").onclick=()=>{speedIndex=(speedIndex+1)%speeds.length;$("#video").playbackRate=speeds[speedIndex];$("#speedBtn").textContent=speeds[speedIndex]+"×"};
$("#nativeBtn").onclick=()=>{$("#video").controls=!$("#video").controls;toast($("#video").controls?"Native controls on":"Native controls off")};
$("#closePlayer").onclick=()=>{$("#video").pause();$("#video").removeAttribute("src");$("#video").load();$("#player").classList.add("hidden");renderContinue()};
function db(){return new Promise((ok,no)=>{const r=indexedDB.open("MovieHub40",1);r.onupgradeneeded=()=>r.result.createObjectStore("videos",{keyPath:"id"});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function getDownloads(){const d=await db();return new Promise((ok,no)=>{const r=d.transaction("videos").objectStore("videos").getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function download(m,u){try{toast("Preparing download…");u=u||await videoUrl(m);const r=await fetch(u);if(!r.ok)throw 0;const b=await r.blob();const d=await db();await new Promise((ok,no)=>{const t=d.transaction("videos","readwrite");t.objectStore("videos").put({id:m.id,title:m.title,year:m.year,g:m.g,blob:b,size:b.size});t.oncomplete=ok;t.onerror=()=>no(t.error)});toast("Saved for offline playback");renderDownloads()}catch(e){window.open(source(m.id),"_blank");toast("Direct save was blocked; opened source page")}}
async function renderDownloads(){const a=await getDownloads();S.downloadCache=a;$("#downloadCount").textContent=a.length;$("#storageUsed").textContent=(a.reduce((n,x)=>n+(x.size||x.blob?.size||0),0)/1048576).toFixed(1)+" MB";$("#downloads").innerHTML=a.map(x=>`<article class="card" data-id="${esc(x.id)}"><div class="poster"><div class="posterFallback">▶</div><span class="tag">OFFLINE</span></div><div class="info"><div class="name">${esc(x.title)}</div><div class="meta">${esc(x.year)} · ${((x.size||x.blob?.size||0)/1048576).toFixed(1)} MB</div><button class="downloadDelete" data-del="${esc(x.id)}">Delete</button></div></article>`).join("");$("#downEmpty").classList.toggle("hidden",a.length>0);$$("#downloads .card").forEach(c=>c.onclick=e=>{if(e.target.dataset.del)return;const x=a.find(z=>z.id===c.dataset.id);if(!x)return;$("#video").src=URL.createObjectURL(x.blob);$("#now").textContent=x.title;$("#status").textContent="Offline playback";S.cur={id:x.id,title:x.title};$("#player").classList.remove("hidden");$("#video").play().catch(()=>{})});$$("[data-del]").forEach(b=>b.onclick=async e=>{e.stopPropagation();const d=await db();await new Promise((ok,no)=>{const t=d.transaction("videos","readwrite");t.objectStore("videos").delete(b.dataset.del);t.oncomplete=ok;t.onerror=()=>no(t.error)});toast("Download deleted");renderDownloads()})}
function renderProfiles(){$("#profiles").innerHTML=S.profiles.map(p=>`<div class="profile ${p.id===S.profile?"active":""}"><div class="profileAvatar">${esc(p.avatar)}</div><b>${esc(p.name)}</b><small>${p.id===S.profile?"Active profile":"Local profile"}</small><button data-profile="${esc(p.id)}">${p.id===S.profile?"Selected":"Switch"}</button></div>`).join("");$$("[data-profile]").forEach(b=>b.onclick=()=>{S.profile=b.dataset.profile;save();renderProfiles();renderHome();toast("Switched to "+activeProfile().name)})}
function nav(n){$$(".view").forEach(v=>v.classList.remove("active"));const id={home:"home",search:"searchView",list:"listView",downloads:"downloadsView",profile:"profileView"}[n]||"home";$("#"+id).classList.add("active");$$("nav button").forEach(b=>b.classList.toggle("active",b.dataset.nav===n));if(n==="downloads")renderDownloads();if(n==="profile")renderProfiles();if(n==="search"){renderSearch();$("#q").focus()}window.scrollTo(0,0)}
$$("[data-nav]").forEach(b=>b.onclick=()=>nav(b.dataset.nav));
$("#profileBtn").onclick=()=>nav("profile");
$("#q").oninput=e=>{S.q=e.target.value.trim();nav("search")};
$("#browse").onclick=()=>{$("#trending").scrollIntoView({behavior:"smooth"})};
$("#surprise").onclick=()=>{const a=filtered();if(a.length)detail(a[Math.floor(Math.random()*a.length)].id)};
$("#clearHistory").onclick=()=>{S.history[profileKey()]={};save();renderContinue();toast("Viewing history cleared")};
$("#clearList").onclick=()=>{S.list[profileKey()]=[];save();renderHome();toast("My List cleared")};
$("#kids").onclick=e=>{S.kids=!S.kids;e.currentTarget.querySelector("span").textContent=S.kids?"ON":"OFF";toast(S.kids?"Kids Mode on":"Kids Mode off")};
$("#clearAllData").onclick=()=>{if(confirm("Reset MovieHub data on this device?")){localStorage.removeItem(KEY);location.reload()}};
load();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
